# Generated by Django 3.1.7 on 2021-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_choosing', models.BooleanField(default=False)),
                ('post_time_in', models.DateTimeField(auto_now_add=True)),
                ('post_title', models.CharField(max_length=255, unique=True)),
                ('post_text', models.CharField(max_length=255)),
                ('post_rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
