# Generated by Django 3.1.7 on 2021-03-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210324_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_choosing',
            new_name='choosing',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time_in',
            new_name='time_in',
        ),
    ]
