# Generated by Django 3.2 on 2021-04-16 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20210415_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscriber',
            new_name='subscribers',
        ),
    ]
