# Generated by Django 3.1.7 on 2021-07-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
