# Generated by Django 3.2 on 2021-07-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0003_auto_20210710_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
