# Generated by Django 3.2 on 2021-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_search_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Author',
            field=models.CharField(default='Author', max_length=100),
        ),
        migrations.DeleteModel(
            name='search',
        ),
    ]
